[project]
name = "rubiks-cube-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.5",
    "uvicorn[standard]>=0.40.0",
]
